# Generated by Django 4.2.4 on 2023-08-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_created',
        ),
    ]
