# Generated by Django 4.2.4 on 2023-08-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_person_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_created',
        ),
    ]
