# Generated by Django 4.2.4 on 2023-08-27 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_person_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
