# Generated by Django 4.2.4 on 2023-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_person_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='people',
            field=models.ManyToManyField(to='mainapp.person'),
        ),
    ]
